### ISSUE TITLE
established connection breaks almost immediately

### ISSUE THREAD

**Issue by yutanicorp** [MisterDaneel/pysoxy#1]
First, thank you for creating this program. I can really use it well, but unfortunately, I stumbled upon a bug.

REPRODUCTION STEPS
1. run pysoxy with Python 3.7.3 on client
2. run proxifier Proxychains4 to proxify SSH through pysoxy bind port
3. the remote host receives connection and shows welcome screen
4. almost immediately the SSH connection breaks (pysoxy keeps running)

I proxified with SSH, but I also tested it with NetCat and there was no difference.

OS: Linux Fedora 29
Hardware: x86_64

One other thing, I work with an excellent IDE called PyCharm and it shows some warnings and one error. I had to remove the "e" on line 61. Please consider using a linter to validate the code.

**Comment by MisterDaneel** [comment]
Hello Vincent,

Thank you for your feedback, I will try to reproduce and fix the bug
as soon as I have some time. Maybe next weekend.

Regards,

Daneel

**Comment by yutanicorp** [comment]
Thank for your efforts in advance, Daneel! I am looking forward to seeing the fixed version.

**Comment by MisterDaneel** [comment]
I assume the bug is now fixed. Please tell me if you continue to get some issues.

Regards
