### ISSUE TITLE
(enhancement) 

### ISSUE THREAD

**Issue by Anonymous2716** [MisterDaneel/pysoxy#6]
Hi MisterDaneel 
I appreciate your code . I was thinking if I could block few IPs or let pass through only the IPs I want .it would be great . Thanks.

**Comment by csenjoyer1337** [comment]
Yeah, this would be useful

**Comment by ghost** [comment]
### Decline Requests from specific sources
On the main function simply add

```python
try:        
    wrapper, _ = new_socket.accept()
    wrapper.setblocking(1)
    if __[0] == "127.0.0.1": 
        wrapper.close()
``` 
or create list list with IPs
```python
if __[0] in blacklist:
    wrapper.close()
```
### Or to whilelist change it to that
```python
if __[0] not in whilelist:
    wrapper.close()
```

**Comment by Anonymous2716** [comment]
@senshiofficial would this also work if i use domain names? Or whatever is requested by the client? Thanks .

**Comment by ghost** [comment]
> @senshiofficial would this also work if i use domain names? Or whatever is requested by the client? Thanks .

If a device or a Server is connecting to your Proxy it will always be a IP, if you want to block the destination which includes IPs and Domains you could try that
at the `request_client()` function simply add
### Blocklist Servers from being requested
```python
if dst_addr == "Domain.com" or dst_addr in blacklist:
    return 0
```
you could also blocklist a port for whatever reason you wanna do that
```python
if str(dst_port) == "80" or str(dst_port) in blacklistports:
    return 0
```
Just simply add that before `return (dst_addr, dst_port)`

**Comment by Anonymous2716** [comment]
@senshiofficial thanks I will try testing later.
