### ISSUE TITLE
Doesn't work on windows.

### ISSUE THREAD

**Issue by Anonymous2716** [MisterDaneel/pysoxy#7]
Windows 7
Python 2.7 
Netstat shows that my phone is connected to the PC on port 9050 . But pysoxy doesn't receive or send anything to my phone.and if I run this on my phone it just works for localhost with the app PCAPDROID but can't connect from the PC. OR any other socks proxy client app.

**Comment by ghost** [comment]
the tool is made for Python3. you could try installing python3.10 and are you hosting port 9050 on your PC? if yes are you trying to use TOR?

**Comment by Anonymous2716** [comment]
@senshiofficial  i tried with python 3.I believe it was some firewall issue. I guess I can close this issue. Thanks anyway. I don't own a windows device anymore. Currently using this useful script on Linux with python 3.11.
