### ISSUE TITLE
which var has the data thats been send and respond from the server?

### ISSUE THREAD

**Issue by ghost** [MisterDaneel/pysoxy#9]
Yeah so basically im trying to edit/see the data transmitted from the client to the server.
i tried to do `print("DATA {}".format(data))` at `proxy_loop()` but it seems to only show the response from an HTTP request. if i try for example `proxychains nmap 192.168.2.1 -p 80` it doesnt show anything.

Great tool btw, although its 4 years old

**Comment by Anonymous2716** [comment]
I tested using netcat and proxychains.  And this is what I got.

```
if sock is socket_dst:
    socket_src.send(data)
    print("response from the server: ", data)
else:
    socket_dst.send(data)
    print("request from the client: ", data)
```
And I don't think it prints anything if theres no actual socket connection . nmap doesn't create connections rather it does something similar to pinging. If you use netstat you can see it. I'm not sure exactly what happens but this is what I think happens.

**Comment by ghost** [comment]
yeah @Anonymous2716  youre right lol i almost forgot. thx
